In [1]:
using PyCall
pyscf = pyimport("pyscf")
geomopt = pyimport("pyscf.geomopt.geometric_solver")

PyObject <module 'pyscf.geomopt.geometric_solver' from '/home/marcus/.local/lib/python3.8/site-packages/pyscf/geomopt/geometric_solver.py'>

In [2]:
function searchkeys(s, o)
    filter(startswith(s), String.(keys(o)))
end

searchkeys (generic function with 1 method)

In [3]:
mol = pyscf.gto.M(atom="N 0 0 0; H 1 0 0; H 0 1 0; H 0 0 1"; basis="sto3g")

PyObject <pyscf.gto.mole.Mole object at 0x7f41f82af820>

In [4]:
hf = mol.RHF().run()

converged SCF energy = -55.4292886810922


PyObject RHF object of <class 'pyscf.scf.hf.RHF'>

In [5]:
mol_opt = geomopt.optimize(hf)


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   1.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   0.000000   1.000000   0.000000    0.000000  0.000000  0.000000
   H   0.000000   0.000000   1.000000    0.000000  0.000000  0.000000
converged SCF energy = -55.4292886810922
--------------- SCF_Scanner gradients ---------------
         x                y                z
0 N    -0.0047841309    -0.0047841309    -0.0047841309
1 H    -0.0572267086     0.0310054198     0.0310054198
2 H     0.0310054198    -0.0572267086     0.0310054198
3 H     0.0310054198     0.0310054198    -0.0572267086
----------------------------------------------
cycle 1: E = -55.4292886811  dE = -55.4293  norm(grad) = 0.125145

Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY  


                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ********      .))))))  
          ##      .%%%%%%/      (%%%%%%,                  ,******      /)))))  
        %%%%%%      .%%%%%%#      *%%%%%%,    ,/////.       ******      )))))) 
      #%      %%      .%%%%%%/      *%%

PyObject <pyscf.gto.mole.Mole object at 0x7f41e02a95e0>

In [6]:
hf_opt = mol_opt.RHF().run()

converged SCF energy = -55.4554197787915


PyObject RHF object of <class 'pyscf.scf.hf.RHF'>

In [7]:
h = hf_opt.Hessian().hess()

4×4×3×3 Array{Float64, 4}:
[:, :, 1, 1] =
  0.672616   -0.534562   -0.0690271    -0.0690271
 -0.534562    0.548876   -0.0071567    -0.0071567
 -0.0690271  -0.0071567   0.0768052    -0.000621358
 -0.0690271  -0.0071567  -0.000621358   0.0768052

[:, :, 2, 1] =
 -0.168203    0.108722     0.0317339   0.0277467
  0.0317339  -0.0842462    0.064731   -0.0122187
  0.108722   -0.0206893   -0.0842462  -0.00378701
  0.0277467  -0.00378701  -0.0122187  -0.0117409

[:, :, 3, 1] =
 -0.168203    0.108722     0.0277467    0.0317339
  0.0317339  -0.0842462   -0.0122187    0.064731
  0.0277467  -0.00378701  -0.0117409   -0.0122187
  0.108722   -0.0206893   -0.00378701  -0.0842462

[:, :, 1, 2] =
 -0.168203    0.0317339   0.108722     0.0277467
  0.108722   -0.0842462  -0.0206893   -0.00378701
  0.0317339   0.064731   -0.0842462   -0.0122187
  0.0277467  -0.0122187  -0.00378701  -0.0117409

[:, :, 2, 2] =
  0.672616   -0.0690271    -0.534562   -0.0690271
 -0.0690271   0.0768052    -0.0071567  -0.0006213

In [8]:
using LinearAlgebra

In [9]:
hp = PermutedDimsArray(h, (3, 1, 4, 2))

3×4×3×4 PermutedDimsArray(::Array{Float64, 4}, (3, 1, 4, 2)) with eltype Float64:
[:, :, 1, 1] =
  0.672616  -0.534562   -0.0690271  -0.0690271
 -0.168203   0.0317339   0.108722    0.0277467
 -0.168203   0.0317339   0.0277467   0.108722

[:, :, 2, 1] =
 -0.168203   0.108722    0.0317339   0.0277467
  0.672616  -0.0690271  -0.534562   -0.0690271
 -0.168203   0.0277467   0.0317339   0.108722

[:, :, 3, 1] =
 -0.168203   0.108722    0.0277467   0.0317339
 -0.168203   0.0277467   0.108722    0.0317339
  0.672616  -0.0690271  -0.0690271  -0.534562

[:, :, 1, 2] =
 -0.534562   0.548876   -0.0071567   -0.0071567
  0.108722  -0.0842462  -0.0206893   -0.00378701
  0.108722  -0.0842462  -0.00378701  -0.0206893

[:, :, 2, 2] =
  0.0317339  -0.0842462   0.064731   -0.0122187
 -0.0690271   0.0768052  -0.0071567  -0.000621358
  0.0277467  -0.0117409  -0.0122187  -0.00378701

[:, :, 3, 2] =
  0.0317339  -0.0842462  -0.0122187     0.064731
  0.0277467  -0.0117409  -0.00378701   -0.0122187
 -0.0690271 

In [10]:
hm = reshape(hp, 12, 12)

12×12 reshape(PermutedDimsArray(::Array{Float64, 4}, (3, 1, 4, 2)), 12, 12) with eltype Float64:
  0.672616   -0.168203   -0.168203   …   0.0277467     0.108722
 -0.168203    0.672616   -0.168203      -0.0690271     0.108722
 -0.168203   -0.168203    0.672616       0.0317339    -0.534562
 -0.534562    0.108722    0.108722      -0.00378701   -0.0206893
  0.0317339  -0.0690271   0.0277467     -0.000621358  -0.00378701
  0.0317339   0.0277467  -0.0690271  …  -0.0122187    -0.0071567
 -0.0690271   0.0317339   0.0277467     -0.0122187    -0.00378701
  0.108722   -0.534562    0.108722      -0.0071567    -0.0206893
  0.0277467   0.0317339  -0.0690271      0.064731     -0.0071567
 -0.0690271   0.0277467   0.0317339     -0.0117409    -0.0842462
  0.0277467  -0.0690271   0.0317339  …   0.0768052    -0.0842462
  0.108722    0.108722   -0.534562      -0.0842462     0.548876

In [11]:
e, v = eigen(hm)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
12-element Vector{Float64}:
 -1.043484946102285e-6
 -1.013753465178695e-6
 -1.0137534275764687e-6
 -3.7554342288146624e-13
  1.4742769500912322e-13
  5.17293845755803e-13
  0.18308352049970966
  0.2079281660581723
  0.20792816605852532
  0.7653602764059774
  1.3805047997386908
  1.3805047997391253
vectors:
12×12 Matrix{Float64}:
 -2.28026e-7   0.214984    0.0185758  …   0.337435   -0.630365     0.0134555
  4.52589e-7  -0.122253    0.176784       0.337435    0.300923    -0.552701
 -1.88553e-7  -0.0927307  -0.195359       0.337435    0.329442     0.539246
 -3.91431e-7   0.375879    0.0324781     -0.460345    0.510094    -0.0108882
 -0.408249     0.488291   -0.0202572      0.0614553  -0.0521642    0.0398766
  0.408248     0.478452    0.103789   …   0.0614553  -0.0541878   -0.0376065
  0.408249    -0.32616     0.361825       0.0614553   0.0594384   -0.0279698
  7.4945e-7   -0.213748    0.30909       -0.460345   -0.243508    

In [13]:
reshape(v, 3, 4, 12)

3×4×12 Array{Float64, 3}:
[:, :, 1] =
 -2.28026e-7  -3.91431e-7   0.408249   -0.408249
  4.52589e-7  -0.408249     7.4945e-7   0.408248
 -1.88553e-7   0.408248    -0.408247   -3.22009e-7

[:, :, 2] =
  0.214984   0.375879  -0.32616   -0.264703
 -0.122253   0.488291  -0.213748  -0.15229
 -0.0927307  0.478452  -0.22359   -0.162131

[:, :, 3] =
  0.0185758   0.0324781  0.361825  -0.412879
  0.176784   -0.0202572  0.30909   -0.465616
 -0.195359    0.103789   0.433138  -0.341568

;;; … 

[:, :, 10] =
 0.337435  -0.460345    0.0614553   0.0614553
 0.337435   0.0614553  -0.460345    0.0614553
 0.337435   0.0614553   0.0614553  -0.460345

[:, :, 11] =
 -0.630365   0.510094    0.0594384    0.0608324
  0.300923  -0.0521642  -0.243508    -0.00525057
  0.329442  -0.0541878  -0.00866817  -0.266586

[:, :, 12] =
  0.0134555  -0.0108882  -0.0279698   0.0254026
 -0.552701    0.0398766   0.447249    0.0655763
  0.539246   -0.0376065  -0.0652792  -0.43636